https:
  - servers:
      - listen: "80"
        server_name: "your_domain.com"
        locations:
          - path: "/"
            proxy_pass: "http://backend_server"
            proxy_http_version: "1.1"
            proxy_set_header:
              upgrade: "$http_upgrade"
              connection: "'upgrade'"
              host: "$host"
    upstreams:
      - name: backend_server
        addresses:
          - server: "backend1.example.com"
            weight: 5
          - server: "127.0.0.1:8080"
            max_fails: 3
            fail_timeout: "30s"
          - server: "unix:/tmp/backend3"
          - server: "backup1.example.com"
            backup: true